---
title: "Simple document"
output: github_document
---

I'm an R Markdown document! 

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

I want to improt 'FAS_litters.csv'.

```{r}

litters_df = read_csv("data/FAS_litters.csv")
```

I want better name.
```{r}
names(litters_df)
litters_df = janitor::clean_names(litters_df)
#do not need to import whole janitor library
```

Look at the dataset

```{r}
view(litters_df)
```

Summery information -- 'skimr'
```{r}
skimr::skim(litters_df)
```

## Arguments in 'read_csv'
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv",
           skip = 5,
           col_names = FALSE,
           na = "Low8"
  
)
```

## parsing columns.
```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )

)
litters_data
```
## Reading from Excel
```{r}

mlbll_df = readxl::read_excel("data/mlb11.xlsx")
```

LotR Words is next.

```{r}
fellow_df = readxl::read_excel("data/LotR_Words.xlsx")
fellow_df1 = readxl::read_excel("data/LotR_Words.xlsx",)

```

## Read a SAS file
```{r}
# need to import 'haven'
#pulse_df = read_sas("data/public_pulse_data.sas7bdat")
#???? Failed
```

## why to never use 'read_csv'
```{r}
litters_df_base = read.csv("data/FAS_litters.csv")
# dataframe but not tibble. tibble has more information.
```

