---
title: "Tidy_data"
output: github_document
---

I'm an R Markdown document! 

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

## pivot longer

```{r}

pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
```
try to pivot
```{r}
pulse_tidy = 
  pulse_df %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = 'visit',
    names_prefix = 'bdi_score_',
    values_to = 'bdi'
  ) %>%
  mutate(
    visit = replace(visit, visit == "bl", '00m')
  )
```
##pivot_wider
```{r}
analysis_df =
  tibble(
    group = c('treatment', 'treatment','control','control'),
    time = c('a','b','c','d'),
    group_mean = c(4,8,3,6) 
    #kniter::kable()?
    )

 
```
(no 'spread()' akways 'pivot_wider()')

## bind_rows
import LotR movie
```{r}
fellowship_df =
  read_excel('data/LotR_Words.xlsx', range = 'B3:D6') %>%
  mutate(movie = ' fellowship_rings')

two_towers_df =
  read_excel('data/LotR_Words.xlsx', range = 'F3:H6') %>%
  mutate(movie = ' two_towers')#?

return_king_df =
  read_excel('data/LotR_Words.xlsx', range = 'J3:L6') %>%
  mutate(movie = ' return_king')

lotr_df =
  bind_rows(fellowship_df, two_towers_df, return_king_df) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "sex", 
    values_to = "words"
  ) %>%
#  mutate(race = str_to_lower(race))  
  relocate(movie)

```
(never use rbind(), always use 'bind_rows()'.)

## join
```{r}
pups_df = 
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(
    sex = recode(sex, `1` = "male", `2` = "female"), #'1' say that is a variable but not number.
    sex = factor(sex)) 
litters_df = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))
```

Let's join them up.
```{r}
fas_df =
  left_join(pups_df, litters_df, by = 'litter_number') %>%
  relocate(litter_number, dose, day_of_tx) #?
#运行后不输出，knit无viewer
```

