---
title: "Simple document"
output: github_document
---

I'm an R Markdown document! 

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

I want to improt 'FAS_litters.csv'.

```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```



##'select'
```{r}

select(litters_data, group, litter_number)

pull(litters_data, group)
```

Let's get rid of rows "and": &, "or": |
```{r}
filter(litters_data, gd_of_birth == 20)
filter(litters_data, gd0_weight < 21)
filter(litters_data, group %in% c('Con7','Con8'))
filter(litters_data, gd_of_birth == 20, group == "Con7")

drop_na(litters_data, gd0_weight)
```

## mutate
add or change columns
```{r}
a =mutate(litters_data, 
          weight_change = gd18_weight- gd0_weight,
          group = str_to_lower(group))
```

rearrange
```{r}
arrange(litters_data, gd_of_birth, gd0_weight)
```
pipes
```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)
```
```{r}
Sys.setenv(LANGUAGE = "en")
```

