---
title: "group by and summarize"
output: github_document
---


```{r}
library(tidyverse)

```
Loading dataset 
```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```



## `group_by`
```{r}
weather_df %>%
  group_by(name, month)
```
## count some things
```{r}
# tidy for analysis
weather_df %>%
  group_by(month, name) %>%
  summarise(n_obs = n())

weather_df %>%
  count(name)
   
```

data frame don't use `table`
```{r}
weather_df %>%
  janitor::tabyl(month, name)
# better than `table` wider not tidy for read.
```

## more genral summaries 
```{r}
weather_df %>%
  group_by( name, month) %>%
  summarise(
    n_obs = n(),
    mean_tmax = mean(tmax,na.rm = TRUE),
    median_tmax = median(tmax,na.rm = TRUE) ,
    sd_tmax = sd(tmax,na.rm = TRUE) ) %>%
    ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```
formatting table outputs
```{r}
weather_df %>%
  group_by( name, month) %>%
  summarise(
    n_obs = n(),
    mean_tmax = mean(tmax,na.rm = TRUE)) %>%
  knitr::kable(digits = 2)
```

What about tmax and tmin
```{r}

```

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  select(id, visit, everything()) %>%
  mutate(
    visit = recode(visit, "bl" = "00m"),
    visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id, visit)

pulse_df %>%
  ggplot(aes(x = visit, y = bdi)) +
  geom_boxplot()
```

```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3)

fas_data = left_join(pup_data, litter_data, by = "litter_number") 

fas_data %>% 
  select(sex, dose, day_of_tx, pd_ears:pd_walk) %>% 
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome", 
    values_to = "pn_day") %>% 
  drop_na() %>% 
  mutate(outcome = forcats::fct_reorder(outcome, pn_day, median)) %>% 
  ggplot(aes(x = dose, y = pn_day)) + 
  geom_violin() + 
  facet_grid(day_of_tx ~ outcome)
```

